# Chemin du dossier racine du dataset
path: '../../static'  

# Chemins des dossiers de données pour l'entraînement, validation, et test (relatifs au 'path')
train: images 
val: images  
test: images  

# Définition des classes de poinçons avec leur nom et leur identifiant
names:
  0: R-concentriques
  1: R-rayons
  2: R-chevrons
  3: R-motifs
  4: P-feuille
  5: P-triangle
  6: P-contour-triangle
  7: P-union-jack
  8: P-autres
  9: P-vertical
  10: Pointillés
  11: C-a-points
  12: C-a-points-blanc
  13: P-vertical-variation
  14: M-carres
  15: Spiderman
  16: autres-fig
  17: Arceaux
  18: Rouelles
  19: Palmettes
  20: Colonnettes
  21: Geo
  22: R-chevrons-variation
